set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER clang)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_C_USING_LINKER_LLD "-fuse-ld=lld")
set(CMAKE_ASM_USING_LINKER_LLD "-fuse-ld=lld")
set(CMAKE_LINKER_TYPE LLD)

set(CMAKE_C_COMPILER_TARGET x86_64-elf)
set(CMAKE_ASM_COMPILER_TARGET x86_64-elf)

set(CMAKE_C_FLAGS_INIT "-ffreestanding -nostdlib")
set(CMAKE_ASM_FLAGS_INIT "-ffreestanding")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
